@bananana
let a = a | b | c;

let asd = (asd);

let c = "bbasdas";


// asdasdas d

// asdasda my hands...

/*  Hi there
    How are you?
    I am well...
    Good for you...
    This is a very long comment, isnt it?

    ...

    Yep.
 */

@Ignored
let pa = "bbasdas" banana ;


@Ignored
let bb = bb | "aaa" | asd  ;

let ccc = (a b) | c ;

let dddd = "Asdasd \"";

@Literal
let eeeee = '''asdas \' ''';

@Literal
let dfas = "dasda";

let f = "asdasdasd"*;

let g = !('x' | 'x' | 's' | 's' | 'a') waffle;

let h = ['s'..'d'] banana;

let foldedSample = a
                   | bacon
                   | f;

let bacon = "a"{5,9};

let toast = asdasd;

let banana = asd;

let ajsd = bacon roll;


let m = n;
let n = o;
let o = m;
